### ISSUE TITLE
Remove Bisect Hosting ad from Modrinth page

### ISSUE THREAD

**Issue by TheGreenSquare** [LieOnLion/More-Furnace-Variants#1]
You have a Patreon, use it. It's better than shilling for a shitty server company.

**Comment by AzureDoom** [comment]
> You have a Patreon, use it. It's better than shilling for a shitty server company.

Damn, who pissed in your Wheaties?
![7e4](https://github.com/LieOnLion/More-Furnace-Variants/assets/7415711/7cb077b1-bf03-478a-8279-e83d4971520d)

**Comment by kreezxil** [comment]
if i had a nickel for everytime someone suggested I use patreon, I'd have no nickels at all. Bisect is a top notch server company. If you had issues with them, maybe look in the mirror. They have 24/7 support via tickets. They will get started on your ticket within 20 minutes of you submitting it, not a week later. If you don't mind learning how to manage problems yourself, their Discord is lit with very happy customers that will gladly help you learn how to manage issues on your own. They'll ask you for things, you need to be able to read and comprehend what they are asking for, those customers are not staff, they do not have access to your server.

On top of that BH never oversells a node, unlike other major server hosting companies. And they'll move you to a new node for free and they won't fuss about it. If you have a node in france but discover all your players are from texas, no problem, submit a ticket to get it moved to dallas. It's as easy as that.

That's the tip of the iceberg.

Also, yeah, don't be salty. Nobody likes a salty lollipop.

**Comment by LightBlueGamer** [comment]
I love Bisect, they've helped me out so much hell today alone I've spent like a good 12 hours talking with their support team while they try to help me fix my issue with my server, cheers for Bisect for having an amazing support team #BisectSimpNm1FanUwUHireMeBisect

**Comment by 704Prod** [comment]
> You have a Patreon, use it. It's better than shilling for a shitty server company.

Why are you crying over an ad LMFAO. It's a free mod dude. Let them earn their money. It's not gambling, it's not drugs. It's a hosting company with a solid reputation. Go outside.

**Comment by omo50** [comment]
> You have a Patreon, use it. It's better than shilling for a shitty server company.

Thanks to this, you have successfully caused an issue for every mod and modpack developer on the planet. Thanks man

**Comment by sammwyy** [comment]
> You have a Patreon, use it. It's better than shilling for a shitty server company.

You literally created a problem for the Minecraft modding scene, congratulations, retard. Why can't you stop crying about things that don't matter or affect you? Think about that when you go to sleep and how pathetic you are becoming.

**Comment by makumaku1974** [comment]
*My honest reaction:*
![image](https://github.com/user-attachments/assets/e21446d6-23b2-4933-9358-4084743a18fd)
